package precommit

import (
	"os"
	"path/filepath"
	"testing"
)

func writeConfig(t *testing.T, root string) {
	t.Helper()
	if err := os.WriteFile(filepath.Join(root, ".pre-commit-config.yaml"), []byte("repos: []\n"), 0o644); err != nil {
		t.Fatal(err)
	}
}

func writeInstalledHook(t *testing.T, root string) {
	t.Helper()
	hooks := filepath.Join(root, ".git", "hooks")
	if err := os.MkdirAll(hooks, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(hooks, "pre-commit"), []byte("# File generated by pre-commit\n"), 0o755); err != nil {
		t.Fatal(err)
	}
}

func TestCheckNoConfigSkips(t *testing.T) {
	root := t.TempDir()
	r := newFakeRunner()
	res, err := Check(r, Options{Root: root})
	if err != nil {
		t.Fatalf("Check() error = %v", err)
	}
	if res.ConfigFound {
		t.Fatal("ConfigFound should be false")
	}
	if !res.OK {
		t.Fatal("no config should be OK (skipped)")
	}
}

func TestCheckMissingToolNoInstall(t *testing.T) {
	root := t.TempDir()
	writeConfig(t, root)
	r := newFakeRunner()
	res, err := Check(r, Options{Root: root, AllowInstall: false})
	if err != nil {
		t.Fatalf("Check() error = %v", err)
	}
	if res.ToolInstalled {
		t.Fatal("ToolInstalled should be false")
	}
	if res.OK {
		t.Fatal("missing tool without install should not be OK")
	}
	if len(res.ActionsTaken) != 0 {
		t.Fatalf("no actions should be taken, got %v", res.ActionsTaken)
	}
}

func TestCheckAllReady(t *testing.T) {
	root := t.TempDir()
	writeConfig(t, root)
	writeInstalledHook(t, root)
	r := newFakeRunner()
	r.responses[key("pre-commit", "--version")] = fakeResp{out: "pre-commit 3.7.0\n"}
	res, err := Check(r, Options{Root: root})
	if err != nil {
		t.Fatalf("Check() error = %v", err)
	}
	if !res.OK || !res.ConfigFound || !res.ToolInstalled || !res.HookInstalled {
		t.Fatalf("expected fully ready result, got %+v", res)
	}
	if res.ToolVersion != "3.7.0" {
		t.Fatalf("ToolVersion = %q", res.ToolVersion)
	}
}

func TestCheckInstallsHookWhenAllowed(t *testing.T) {
	root := t.TempDir()
	writeConfig(t, root)
	r := newFakeRunner()
	r.responses[key("pre-commit", "--version")] = fakeResp{out: "pre-commit 3.7.0\n"}
	r.responses[key("pre-commit", "install")] = fakeResp{out: "ok"}
	hookWriter := &hookInstallingRunner{fakeRunner: r, root: root}

	res, err := Check(hookWriter, Options{Root: root, AllowInstall: true})
	if err != nil {
		t.Fatalf("Check() error = %v", err)
	}
	if !res.HookInstalled || !res.OK {
		t.Fatalf("expected hook installed + OK, got %+v", res)
	}
	if len(res.ActionsTaken) == 0 {
		t.Fatal("expected an action recorded for hook install")
	}
}

func TestCheckRunFails(t *testing.T) {
	root := t.TempDir()
	writeConfig(t, root)
	writeInstalledHook(t, root)
	r := newFakeRunner()
	r.responses[key("pre-commit", "--version")] = fakeResp{out: "pre-commit 3.7.0\n"}
	r.responses[key("pre-commit", "run", "--all-files")] = fakeResp{out: "black....Failed", err: errExit{}}

	res, err := Check(r, Options{Root: root, Run: true})
	if err != nil {
		t.Fatalf("Check() error = %v", err)
	}
	if res.RunResult != "failed" {
		t.Fatalf("RunResult = %q, want failed", res.RunResult)
	}
	if res.OK {
		t.Fatal("failed run should make result not OK")
	}
}

func TestCheckRunPasses(t *testing.T) {
	root := t.TempDir()
	writeConfig(t, root)
	writeInstalledHook(t, root)
	r := newFakeRunner()
	r.responses[key("pre-commit", "--version")] = fakeResp{out: "pre-commit 3.7.0\n"}
	r.responses[key("pre-commit", "run", "--all-files")] = fakeResp{out: "all passed"}
	res, err := Check(r, Options{Root: root, Run: true})
	if err != nil {
		t.Fatalf("Check() error = %v", err)
	}
	if res.RunResult != "passed" {
		t.Fatalf("RunResult = %q, want passed", res.RunResult)
	}
	if !res.OK {
		t.Fatal("expected OK after passing run")
	}
}

type errExit struct{}

func (errExit) Error() string { return "exit status 1" }

// hookInstallingRunner writes a pre-commit hook file when `pre-commit install` runs,
// simulating the real tool's side effect.
type hookInstallingRunner struct {
	*fakeRunner
	root string
}

func (h *hookInstallingRunner) Run(dir, name string, args ...string) (string, error) {
	out, err := h.fakeRunner.Run(dir, name, args...)
	if name == "pre-commit" && len(args) == 1 && args[0] == "install" {
		writeInstalledHookNoT(h.root)
	}
	return out, err
}

func writeInstalledHookNoT(root string) {
	hooks := filepath.Join(root, ".git", "hooks")
	_ = os.MkdirAll(hooks, 0o755)
	_ = os.WriteFile(filepath.Join(hooks, "pre-commit"), []byte("# File generated by pre-commit\n"), 0o755)
}
