package precommit

import (
	"os"
	"path/filepath"
	"strings"
)

// configNames lists accepted pre-commit config filenames, in priority order.
var configNames = []string{".pre-commit-config.yaml", ".pre-commit-config.yml"}

// ConfigFile returns the path to the pre-commit config in root, and whether one exists.
func ConfigFile(root string) (string, bool) {
	for _, name := range configNames {
		p := filepath.Join(root, name)
		if info, err := os.Stat(p); err == nil && !info.IsDir() {
			return p, true
		}
	}
	return "", false
}

// ToolVersion returns the installed pre-commit version (e.g. "3.7.0") and whether
// the tool is available.
func ToolVersion(r CommandRunner) (string, bool) {
	out, err := r.Run("", "pre-commit", "--version")
	if err != nil {
		return "", false
	}
	fields := strings.Fields(strings.TrimSpace(out))
	if len(fields) >= 2 {
		return fields[1], true
	}
	if len(fields) == 1 {
		// Output had only the program name with no version token. Treat the
		// tool as installed with an unknown version rather than mislabeling the
		// program name as a version string.
		return "", true
	}
	return "", false
}

// hookSignature is the marker the pre-commit tool writes into the hook file it
// generates. Anchoring on this avoids treating a foreign/custom hook that merely
// mentions "pre-commit" as one managed by the tool.
const hookSignature = "generated by pre-commit"

// HookInstalled reports whether the repository's pre-commit git hook exists and was
// generated by the pre-commit tool. root is the repository root; r is used to
// resolve the real hooks path so git worktrees (where .git is a file) work.
func HookInstalled(r CommandRunner, root string) bool {
	data, err := os.ReadFile(hookPath(r, root))
	if err != nil {
		return false
	}
	return strings.Contains(string(data), hookSignature)
}

// hookPath resolves the path to the pre-commit hook, honoring git worktrees by
// asking git for the real hooks directory. It falls back to
// <root>/.git/hooks/pre-commit when git cannot be consulted.
func hookPath(r CommandRunner, root string) string {
	out, err := r.Run(root, "git", "rev-parse", "--git-path", "hooks/pre-commit")
	if err == nil {
		if p := strings.TrimSpace(out); p != "" {
			if !filepath.IsAbs(p) {
				p = filepath.Join(root, p)
			}
			// git (notably under git-bash on Windows) may return forward
			// slashes; normalize to the OS separator and remove any "..".
			return filepath.Clean(p)
		}
	}
	return filepath.Join(root, ".git", "hooks", "pre-commit")
}
