# Homebrew Formula for GitCode CLI
#
# This is a local reference copy. The live formula is generated by GoReleaser
# (see .goreleaser.yaml `brews:`) and pushed to gitcode-cli/homebrew-tap by the
# release workflow (see .github/workflows/release.yml `brew` job).
#
# Install with:
#   brew install gitcode-cli/homebrew-tap/gc
#
# The sha256 and version fields here are placeholders; GoReleaser injects the
# real values from the published release artifacts.

class Gc < Formula
  desc "GitCode CLI - Command line tool for GitCode"
  homepage "https://gitcode.com/gitcode-cli/cli"
  version "0.1.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/gitcode-cli/cli/releases/download/v#{version}/gc_#{version}_darwin_amd64.tar.gz"
      sha256 ""
    end
    on_arm do
      url "https://github.com/gitcode-cli/cli/releases/download/v#{version}/gc_#{version}_darwin_arm64.tar.gz"
      sha256 ""
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/gitcode-cli/cli/releases/download/v#{version}/gc_#{version}_linux_amd64.tar.gz"
      sha256 ""
    end
    on_arm do
      url "https://github.com/gitcode-cli/cli/releases/download/v#{version}/gc_#{version}_linux_arm64.tar.gz"
      sha256 ""
    end
  end

  def install
    bin.install "gc"
    bash_completion.install "completions/gc.bash" => "gc"
    zsh_completion.install "completions/gc.zsh" => "_gc"
    fish_completion.install "completions/gc.fish"
  end

  test do
    assert_match "gc version", shell_output("#{bin}/gc version")
  end
end
