#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

AI_ROOT="${REPO_ROOT}/.ai/skills"
CODEX_ROOT="${REPO_ROOT}/.codex/skills"
CLAUDE_ROOT="${REPO_ROOT}/.claude/skills"

usage() {
  cat <<'EOF'
Usage:
  scripts/sync-ai-skills.sh [--check]

Behavior:
  - Sync shared skills from .ai/skills/ into .codex/skills/
  - Create missing Claude adapter placeholders, but never overwrite existing
    .claude/skills/* content
  - In --check mode, report whether sync would change any files
EOF
}

if [[ "${1:-}" == "--help" ]]; then
  usage
  exit 0
fi

CHECK_ONLY=0
if [[ "${1:-}" == "--check" ]]; then
  CHECK_ONLY=1
fi

if [[ ! -d "${AI_ROOT}" ]]; then
  echo "shared skill root not found: ${AI_ROOT}" >&2
  exit 1
fi

changed=0

write_file() {
  local target="$1"
  local content="$2"

  if [[ -f "${target}" ]]; then
    local current
    current="$(cat "${target}")"
    if [[ "${current}" == "${content}" ]]; then
      return 0
    fi
  fi

  changed=1
  if [[ "${CHECK_ONLY}" -eq 0 ]]; then
    printf '%s\n' "${content}" >"${target}"
  fi
}

sync_codex_skill() {
  local skill_name="$1"
  local codex_dir="${CODEX_ROOT}/${skill_name}"
  local target="${codex_dir}/SKILL.md"
  local shared_ref="../../../.ai/skills/${skill_name}/SKILL.md"

  mkdir -p "${codex_dir}"

  local content
  content=$(cat <<EOF
---
name: ${skill_name}
description: |
  Codex adapter for the shared \`${skill_name}\` skill.
  Follow project rules in \`spec/\` and defer scenario details to the
  shared skill source.
---

# Codex adapter: ${skill_name}

Generated by \`scripts/sync-ai-skills.sh\`.

共享源：[\`${shared_ref}\`](${shared_ref})

本文件是 Codex 适配层入口。

约束：

- 项目正式规则以 \`spec/\` 为准
- 共享场景定义以 \`.ai/skills/${skill_name}/SKILL.md\` 为准
- 如需调整跨 AI 共享约束，先修改共享源，再重新运行同步脚本
EOF
)

  write_file "${target}" "${content}"
}

sync_claude_placeholder() {
  local skill_name="$1"
  local claude_dir="${CLAUDE_ROOT}/${skill_name}"
  local target="${claude_dir}/SKILL.md"
  local shared_ref="../../../.ai/skills/${skill_name}/SKILL.md"

  if [[ -f "${target}" ]]; then
    return 0
  fi

  mkdir -p "${claude_dir}"

  local content
  content=$(cat <<EOF
---
name: ${skill_name}
description: |
  Claude adapter placeholder for the shared \`${skill_name}\` skill.
  Follow project rules in \`spec/\` and defer scenario details to the
  shared skill source.
---

# Claude adapter: ${skill_name}

Generated placeholder by \`scripts/sync-ai-skills.sh\`.

共享源：[\`${shared_ref}\`](${shared_ref})

本文件只是 Claude 适配层占位入口。

如果该 skill 需要更完整的 Claude 侧说明，可在后续阶段手工补充，但不得与共享源或 \`spec/\` 冲突。
EOF
)

  write_file "${target}" "${content}"
}

while IFS= read -r -d '' skill_dir; do
  skill_name="$(basename "${skill_dir}")"
  sync_codex_skill "${skill_name}"
  sync_claude_placeholder "${skill_name}"
done < <(find "${AI_ROOT}" -mindepth 1 -maxdepth 1 -type d -print0 | sort -z)

if [[ "${CHECK_ONLY}" -eq 1 ]]; then
  if [[ "${changed}" -eq 1 ]]; then
    echo "sync required"
    exit 1
  fi
  echo "skills already in sync"
  exit 0
fi

if [[ "${changed}" -eq 1 ]]; then
  echo "synced shared skills into adapter layers"
else
  echo "no skill changes needed"
fi
